spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.100.201/wildflyticket/back/config-files.git
          username: ConfigServer
          password: ZoeLNSAjWKZN5zoAcsfX
